
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.airline.service;

import java.util.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import at.jku.ce.airline.test.Adapter;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-12-23T23:50:49.314+01:00
 * Generated source version: 2.3.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "AirlineServiceImplService",
                      portName = "AirlineServiceImplPort",
                      targetNamespace = "http://service.airline.ce.jku.at/",
                      wsdlLocation = "http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl",
                      endpointInterface = "at.jku.ce.airline.service.AirlineServiceImpl")
                      
public class AirlineServiceImplImpl implements AirlineServiceImpl {

    private static final Logger LOG = Logger.getLogger(AirlineServiceImplImpl.class.getName());  
    Adapter a;
    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlight(java.lang.String  flightId )*
     */
    public at.jku.ce.airline.service.Flight getFlight(java.lang.String flightId) { 
        LOG.info("Executing operation getFlight");
        System.out.println(flightId);
         
        try {
        	
        	a = Adapter.getInstance();
        	for(Flight f1 : a.getAirline().getFlightPlan()){
        		if(f1.getFlightId().equals(flightId)) return f1;
        	}
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        return null;
 
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlightplan(*
     */
    public java.util.List<at.jku.ce.airline.service.Flight> getFlightplan() { 
        LOG.info("Executing operation getFlightplan");
        try {
        	a = a.getInstance();
        	return a.getAirline().getFlightPlan();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getAirline(*
     */
    public at.jku.ce.airline.service.Airline getAirline() { 
        LOG.info("Executing operation getAirline");
        try {
        	a = a.getInstance();
            return a.getAirline();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#bookFlight(java.lang.String  bookingUuid ,)java.lang.String  flightId ,)javax.xml.datatype.XMLGregorianCalendar  flightDate )*
     */
    public boolean bookFlight(java.lang.String bookingUuid,java.lang.String flightId,javax.xml.datatype.XMLGregorianCalendar flightDate) { 
        LOG.info("Executing operation bookFlight");
        System.out.println(bookingUuid);
        System.out.println(flightId);
        System.out.println(flightDate);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#cancelFlight(java.lang.String  bookingUuid ,)java.lang.String  flightId )*
     */
    public boolean cancelFlight(java.lang.String bookingUuid,java.lang.String flightId) { 
        LOG.info("Executing operation cancelFlight");
        System.out.println(bookingUuid);
        System.out.println(flightId);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
