
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.airline.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-12-23T23:50:49.314+01:00
 * Generated source version: 2.3.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "AirlineServiceImplService",
                      portName = "AirlineServiceImplPort",
                      targetNamespace = "http://service.airline.ce.jku.at/",
                      wsdlLocation = "http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl",
                      endpointInterface = "at.jku.ce.airline.service.AirlineServiceImpl")
                      
public class AirlineServiceImplImpl implements AirlineServiceImpl {

    private static final Logger LOG = Logger.getLogger(AirlineServiceImplImpl.class.getName());

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlight(java.lang.String  flightId )*
     */
    public at.jku.ce.airline.service.Flight getFlight(java.lang.String flightId) { 
        LOG.info("Executing operation getFlight");
        System.out.println(flightId);
        try {
            at.jku.ce.airline.service.Flight _return = new at.jku.ce.airline.service.Flight();
            at.jku.ce.airline.service.Time _returnArrivalTime = new at.jku.ce.airline.service.Time();
            _returnArrivalTime.setIndexDayOfWeek(-1258205373);
            _returnArrivalTime.setTimeOfDay(-4581606397966631545l);
            _return.setArrivalTime(_returnArrivalTime);
            at.jku.ce.airline.service.Airport _returnArrivesAt = new at.jku.ce.airline.service.Airport();
            _returnArrivesAt.setAirportTax(new java.math.BigDecimal("253162293446873127.8660538931769580572"));
            _returnArrivesAt.setCity("City-1312085626");
            _returnArrivesAt.setCountry("Country-1528632292");
            _returnArrivesAt.setIcao("Icao-126986640");
            _returnArrivesAt.setName("Name-1631593432");
            _return.setArrivesAt(_returnArrivesAt);
            at.jku.ce.airline.service.Airport _returnDepartesFrom = new at.jku.ce.airline.service.Airport();
            _returnDepartesFrom.setAirportTax(new java.math.BigDecimal("3629026564852167217.8193620468488320678"));
            _returnDepartesFrom.setCity("City-1751573234");
            _returnDepartesFrom.setCountry("Country-759440457");
            _returnDepartesFrom.setIcao("Icao107742083");
            _returnDepartesFrom.setName("Name413129355");
            _return.setDepartesFrom(_returnDepartesFrom);
            at.jku.ce.airline.service.Time _returnDepartureTime = new at.jku.ce.airline.service.Time();
            _returnDepartureTime.setIndexDayOfWeek(-1335138718);
            _returnDepartureTime.setTimeOfDay(-1842948607360217874l);
            _return.setDepartureTime(_returnDepartureTime);
            _return.setFlightId("FlightId-1664585403");
            _return.setPlaneName("PlaneName-946145943");
            _return.setStdFee(new java.math.BigDecimal("9007463621902115039.6753328103144699894"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlightplan(*
     */
    public java.util.List<at.jku.ce.airline.service.Flight> getFlightplan() { 
        LOG.info("Executing operation getFlightplan");
        try {
            java.util.List<at.jku.ce.airline.service.Flight> _return = new java.util.ArrayList<at.jku.ce.airline.service.Flight>();
            at.jku.ce.airline.service.Flight _returnVal1 = new at.jku.ce.airline.service.Flight();
            at.jku.ce.airline.service.Time _returnVal1ArrivalTime = new at.jku.ce.airline.service.Time();
            _returnVal1ArrivalTime.setIndexDayOfWeek(-184706902);
            _returnVal1ArrivalTime.setTimeOfDay(-8117226517748477898l);
            _returnVal1.setArrivalTime(_returnVal1ArrivalTime);
            at.jku.ce.airline.service.Airport _returnVal1ArrivesAt = new at.jku.ce.airline.service.Airport();
            _returnVal1ArrivesAt.setAirportTax(new java.math.BigDecimal("5528314534940294954.8629271954696705153"));
            _returnVal1ArrivesAt.setCity("City573978838");
            _returnVal1ArrivesAt.setCountry("Country-590196228");
            _returnVal1ArrivesAt.setIcao("Icao1508414905");
            _returnVal1ArrivesAt.setName("Name1079762513");
            _returnVal1.setArrivesAt(_returnVal1ArrivesAt);
            at.jku.ce.airline.service.Airport _returnVal1DepartesFrom = new at.jku.ce.airline.service.Airport();
            _returnVal1DepartesFrom.setAirportTax(new java.math.BigDecimal("-4761195483153175608.3206770116597622811"));
            _returnVal1DepartesFrom.setCity("City-1354631550");
            _returnVal1DepartesFrom.setCountry("Country-477553393");
            _returnVal1DepartesFrom.setIcao("Icao1822007098");
            _returnVal1DepartesFrom.setName("Name913464658");
            _returnVal1.setDepartesFrom(_returnVal1DepartesFrom);
            at.jku.ce.airline.service.Time _returnVal1DepartureTime = new at.jku.ce.airline.service.Time();
            _returnVal1DepartureTime.setIndexDayOfWeek(-902485318);
            _returnVal1DepartureTime.setTimeOfDay(-1908253332975980869l);
            _returnVal1.setDepartureTime(_returnVal1DepartureTime);
            _returnVal1.setFlightId("FlightId-392701014");
            _returnVal1.setPlaneName("PlaneName-1413082419");
            _returnVal1.setStdFee(new java.math.BigDecimal("-933790224026856946.8998401349157735061"));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#getAirline(*
     */
    public at.jku.ce.airline.service.Airline getAirline() { 
        LOG.info("Executing operation getAirline");
        try {
            at.jku.ce.airline.service.Airline _return = new at.jku.ce.airline.service.Airline();
            java.util.List<at.jku.ce.airline.service.Flight> _returnFlightPlan = new java.util.ArrayList<at.jku.ce.airline.service.Flight>();
            at.jku.ce.airline.service.Flight _returnFlightPlanVal1 = new at.jku.ce.airline.service.Flight();
            at.jku.ce.airline.service.Time _returnFlightPlanVal1ArrivalTime = new at.jku.ce.airline.service.Time();
            _returnFlightPlanVal1ArrivalTime.setIndexDayOfWeek(2041476186);
            _returnFlightPlanVal1ArrivalTime.setTimeOfDay(-6882790162729611564l);
            _returnFlightPlanVal1.setArrivalTime(_returnFlightPlanVal1ArrivalTime);
            at.jku.ce.airline.service.Airport _returnFlightPlanVal1ArrivesAt = new at.jku.ce.airline.service.Airport();
            _returnFlightPlanVal1ArrivesAt.setAirportTax(new java.math.BigDecimal("-2425194581946802137.5147767433333402221"));
            _returnFlightPlanVal1ArrivesAt.setCity("City1804542211");
            _returnFlightPlanVal1ArrivesAt.setCountry("Country-392760402");
            _returnFlightPlanVal1ArrivesAt.setIcao("Icao97345596");
            _returnFlightPlanVal1ArrivesAt.setName("Name1109668487");
            _returnFlightPlanVal1.setArrivesAt(_returnFlightPlanVal1ArrivesAt);
            at.jku.ce.airline.service.Airport _returnFlightPlanVal1DepartesFrom = new at.jku.ce.airline.service.Airport();
            _returnFlightPlanVal1DepartesFrom.setAirportTax(new java.math.BigDecimal("9174091054597810991.5162027718437627150"));
            _returnFlightPlanVal1DepartesFrom.setCity("City1989913625");
            _returnFlightPlanVal1DepartesFrom.setCountry("Country-1992482654");
            _returnFlightPlanVal1DepartesFrom.setIcao("Icao-1932141026");
            _returnFlightPlanVal1DepartesFrom.setName("Name-1235453297");
            _returnFlightPlanVal1.setDepartesFrom(_returnFlightPlanVal1DepartesFrom);
            at.jku.ce.airline.service.Time _returnFlightPlanVal1DepartureTime = new at.jku.ce.airline.service.Time();
            _returnFlightPlanVal1DepartureTime.setIndexDayOfWeek(2104445724);
            _returnFlightPlanVal1DepartureTime.setTimeOfDay(-4803996117075742653l);
            _returnFlightPlanVal1.setDepartureTime(_returnFlightPlanVal1DepartureTime);
            _returnFlightPlanVal1.setFlightId("FlightId-241434058");
            _returnFlightPlanVal1.setPlaneName("PlaneName-2121057535");
            _returnFlightPlanVal1.setStdFee(new java.math.BigDecimal("8344490270498553032.7195553567411555897"));
            _returnFlightPlan.add(_returnFlightPlanVal1);
            _return.getFlightPlan().addAll(_returnFlightPlan);
            _return.setName("Name-1884788614");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#bookFlight(java.lang.String  bookingUuid ,)java.lang.String  flightId ,)javax.xml.datatype.XMLGregorianCalendar  flightDate )*
     */
    public boolean bookFlight(java.lang.String bookingUuid,java.lang.String flightId,javax.xml.datatype.XMLGregorianCalendar flightDate) { 
        LOG.info("Executing operation bookFlight");
        System.out.println(bookingUuid);
        System.out.println(flightId);
        System.out.println(flightDate);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.airline.service.AirlineServiceImpl#cancelFlight(java.lang.String  bookingUuid ,)java.lang.String  flightId )*
     */
    public boolean cancelFlight(java.lang.String bookingUuid,java.lang.String flightId) { 
        LOG.info("Executing operation cancelFlight");
        System.out.println(bookingUuid);
        System.out.println(flightId);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
