package at.jku.ce.airline.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-12-23T23:50:49.362+01:00
 * Generated source version: 2.3.7
 * 
 */
@WebService(targetNamespace = "http://service.airline.ce.jku.at/", name = "AirlineServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface AirlineServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFlight", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.GetFlight")
    @WebMethod(action = "urn:GetFlight")
    @ResponseWrapper(localName = "getFlightResponse", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.GetFlightResponse")
    public at.jku.ce.airline.service.Flight getFlight(
        @WebParam(name = "flightId", targetNamespace = "")
        java.lang.String flightId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFlightplan", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.GetFlightplan")
    @WebMethod(action = "urn:GetFlightplan")
    @ResponseWrapper(localName = "getFlightplanResponse", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.GetFlightplanResponse")
    public java.util.List<at.jku.ce.airline.service.Flight> getFlightplan();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAirline", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.GetAirline")
    @WebMethod(action = "urn:GetAirline")
    @ResponseWrapper(localName = "getAirlineResponse", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.GetAirlineResponse")
    public at.jku.ce.airline.service.Airline getAirline();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bookFlight", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.BookFlight")
    @WebMethod(action = "urn:BookFlight")
    @ResponseWrapper(localName = "bookFlightResponse", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.BookFlightResponse")
    public boolean bookFlight(
        @WebParam(name = "bookingUuid", targetNamespace = "")
        java.lang.String bookingUuid,
        @WebParam(name = "flightId", targetNamespace = "")
        java.lang.String flightId,
        @WebParam(name = "flightDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar flightDate
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelFlight", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.CancelFlight")
    @WebMethod(action = "urn:CancelFlight")
    @ResponseWrapper(localName = "cancelFlightResponse", targetNamespace = "http://service.airline.ce.jku.at/", className = "at.jku.ce.airline.service.CancelFlightResponse")
    public boolean cancelFlight(
        @WebParam(name = "bookingUuid", targetNamespace = "")
        java.lang.String bookingUuid,
        @WebParam(name = "flightId", targetNamespace = "")
        java.lang.String flightId
    );
}
