package at.jku.ce.airline.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-12-23T23:50:49.370+01:00
 * Generated source version: 2.3.7
 * 
 */
@WebServiceClient(name = "AirlineServiceImplService", 
                  wsdlLocation = "http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl",
                  targetNamespace = "http://service.airline.ce.jku.at/") 
public class AirlineServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.airline.ce.jku.at/", "AirlineServiceImplService");
    public final static QName AirlineServiceImplPort = new QName("http://service.airline.ce.jku.at/", "AirlineServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AirlineServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AirlineServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AirlineServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirlineServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AirlineServiceImpl
     */
    @WebEndpoint(name = "AirlineServiceImplPort")
    public AirlineServiceImpl getAirlineServiceImplPort() {
        return super.getPort(AirlineServiceImplPort, AirlineServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirlineServiceImpl
     */
    @WebEndpoint(name = "AirlineServiceImplPort")
    public AirlineServiceImpl getAirlineServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AirlineServiceImplPort, AirlineServiceImpl.class, features);
    }

}
